### ISSUE TITLE
ipyannotate and widget issues

### ISSUE THREAD

**Issue by ColeDCrawford** [Living-with-machines/MapReader#327]
[StackOverflow thread](https://stackoverflow.com/questions/77318129/model-class-annotationmodel-from-module-ipyannotate-is-loaded-but-can-not-be)

**Describe the bug**
I am using JupyterLab. Out of the box, Jupyter widgets do not work with a new Python 3.10 virtual environment (looks like there are dependencies that will not install on 3.11 and 3.12 unfortunately). To get widgets to work, I needed to upgrade `ipywidgets` to `8.1.1` which is outside of Mapreader's dependency range. The progress bar widgets are now working, but `ipyannotate` is not.

**Describe the bug**
```
[Open Browser Console for more detailed log - Double click to close this message]
Model class 'AnnotationModel' from module 'ipyannotate' is loaded but can not be instantiated
TypeError: s._deserialize_state is not a function
    at f._make_model (http://localhost:8888/static/lab/4416.7b731f09a31472c51429.js?v=7b731f09a31472c51429:1:9711)
```

**Desktop (please complete the following information):**
 - MacOS Ventura 

** Jupyter Environment **
```
JupyterLab v4.0.9
/Users/colecrawford/GitHub/mapreader-exploration/mapreader_env/share/jupyter/labextensions
        keplergl-jupyter v0.3.2 enabled  X
        jupyterlab_pygments v0.3.0 enabled OK (python, jupyterlab_pygments)
        @jupyter-notebook/lab-extension v7.0.6 enabled OK
        @jupyter-widgets/jupyterlab-manager v5.0.9 enabled OK (python, jupyterlab_widgets)


   The following extensions are outdated:
        keplergl-jupyter
        
   Consider checking if an update is available for these packages.

Other labextensions (built into JupyterLab)
   app dir: /Users/colecrawford/GitHub/mapreader-exploration/mapreader_env/share/jupyter/lab
        ipyannotate v0.1.0 enabled OK
```

```
Selected Jupyter core packages...
IPython          : 8.18.1
ipykernel        : 6.27.1
ipywidgets       : 8.1.1
jupyter_client   : 8.6.0
jupyter_core     : 5.5.0
jupyter_server   : 2.12.1
jupyterlab       : 4.0.9
nbclient         : 0.9.0
nbconvert        : 7.12.0
nbformat         : 5.9.2
notebook         : 7.0.6
qtconsole        : 5.5.1
traitlets        : 5.14.0
```

**Comment by rwood-97** [comment]
Hi, thanks for flagging this.

What version of MapReader are you using? 
We just updated to v1.1.0 yesterday which implements a completely new annotation tool and I think it includes updated dependencies for ipywidgets. 

The docs for the new annotation tool are [here](https://mapreader.readthedocs.io/en/latest/User-guide/Annotate.html). Old docs (v1.0.6 or below use the old annotation tool) can still be found [here](https://mapreader.readthedocs.io/en/v1.0.6/User-guide/Annotate.html) or by clicking the `v:latest` in the bottom left corner of the readthedocs page. 

Let me know if the new annotation tool fixes this and if not I will help fix for the old version.

**Comment by kmcdono2** [comment]
@ColeDCrawford - I had the same issue last week, while testing the new annotation tool @rwood-97 mentions above. I uninstalled and reinstalled `ipywidgets` and it did the trick.

**Comment by ColeDCrawford** [comment]
Thanks for the quick response. Upgrading MapReader to `v1.1.0` fixed this - great timing!
